### ISSUE TITLE
Segment Mozillians for email by country

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/part-MakerParty#13]
We want to use Exact Target to send an email or emails to Mozillians only in the 28 EU states.

**Comment by brianking** [comment]
From Jess Davis:

"This is quite easy to do, but there are a lot of things on my plate at the moment. Bringing in Michele here to prioritize this ask to see if it's something we can accommodate in our current sprint.

If not, another idea would be to tailor the message so that all Mozillians can know and care about this EU specific message."

Emailing all Mozillians would more of a plan C for us.

**Comment by brianking** [comment]
Any follow up needed on this one @LucyeoH ?
