### ISSUE TITLE
Finalize wording re: NON EU funding

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/part-MakerParty#20]
- [x] @couci to make page
- [x]  Lucy to write content

**Comment by couci** [comment]
everything has been done here
closing

**Comment by brianking** [comment]
https://wiki.mozilla.org/ReMo/SOPs/Budget/Special_Cases/Maker_Party_EU_2016

There are a few updates / changes I think need to happen here:
- [x] It needs to be more explicit that no budget is available outside the EU. I suggest a separate paragraph that is bolded
- [x] Link to website that is now live https://www.makerparty.community/
- [x] Change Campaign dates from Oct 1 to Nov 30
- [x] Review and possibly change budget layers depending on attendees. I don't think they make sense. For example, in Slovenia, it would cost as much to run an event for 30 ppl as it would for 130 ppl. I suggest having a flat rate for all events

**Comment by LucyeoH-zz** [comment]
@brianking to make updates.

**Comment by brianking** [comment]
@couci please drop text in here that you are using for budget outside EU.

**Comment by LucyeoH-zz** [comment]
- [x] Put on discourse

**Comment by couci** [comment]
Phrasing for both wiki and discourse:
This year Maker Party has a specific focus in the European Union (EU), because of our copyright reform campaign. Therefore, by default, we will not be funding Maker Party events outside the EU that run the prescribed activities because they don't make sense outside the context of the campaign. However, if you are outside the EU and have an exceptional idea on how to build on or amplify those activities, and it requires budget, you can open a budget request and the Review Team will evaluate.

@LucyeoH let me know if you need any help there

**Comment by couci** [comment]
added on discourse, we can close this one
