### ISSUE TITLE
MozFest Signups Follow-up

### ISSUE THREAD

**Issue by brianking** [mozilla/part-MakerParty#31]
We have some signups from the stand at MozFest, and need to reach out the to pitch hosting a Maker Party.

**Comment by brianking** [comment]
@LucyeoH which messaging do you recommend we use, from the Emails doc?

I'm thinking something like in the ['General EU Outreach Email' message](https://docs.google.com/document/d/1mwolk88AZK_YCC-cKFyj6TplqVk94MPFQJj3HoXzJrk/edit#heading=h.beyjib2jk8nu).

**Comment by LucyeoH-zz** [comment]
Hey! How many are there? Would you have bandwidth to do a 15 min meeting with each of them? If so than I'd recommend we use - ["Email with Sign-Ups to Schedule 1:1"](https://docs.google.com/document/d/1mwolk88AZK_YCC-cKFyj6TplqVk94MPFQJj3HoXzJrk/edit#). 

Otherwise I'd recommend using [the draft](https://docs.google.com/document/d/1mwolk88AZK_YCC-cKFyj6TplqVk94MPFQJj3HoXzJrk/edit#) I started based on the 'General EU Outreach Email'  below, do you know if the sign up was to run a Maker Party or just for more info?
